const STOCKS=[
 {code:'1969',name:'高砂熱学工業',price:4220,theme:['データセンター冷却','設備工事'],fund:88,themeScore:94,valuation:70,technical:76,flow:74,catalyst:86,buy:84,upside:42,action:'押し目候補',buyZone:[4050,4180],take:5400,stop:3820,note:'AIデータセンターの冷却・省エネ投資が追い風。受注と利益率を継続確認。'},
 {code:'4052',name:'フィーチャ',price:612,theme:['DMS','車載AI'],fund:62,themeScore:93,valuation:58,technical:66,flow:60,catalyst:88,buy:78,upside:85,action:'監視',buyZone:[560,600],take:980,stop:515,note:'累計ライセンス台数、ライセンス売上、量産案件数、大手OEM案件への移行が最重要。'},
 {code:'3687',name:'フィックスターズ',price:2115,theme:['AI高速化','量子'],fund:82,themeScore:92,valuation:52,technical:73,flow:72,catalyst:84,buy:76,upside:55,action:'押し目待ち',buyZone:[1900,2040],take:2850,stop:1780,note:'高速化ソフトの利益成長と量子・AI案件の実需化を確認。'},
 {code:'3436',name:'SUMCO',price:1650,theme:['半導体ウエハ'],fund:58,themeScore:78,valuation:82,technical:63,flow:61,catalyst:72,buy:75,upside:48,action:'押し目候補',buyZone:[1560,1640],take:2180,stop:1460,note:'シリコンウエハ市況の底打ちと稼働率回復が焦点。'},
 {code:'5803',name:'フジクラ',price:4650,theme:['光電融合','データセンター'],fund:95,themeScore:97,valuation:45,technical:84,flow:88,catalyst:90,buy:71,upside:36,action:'過熱注意',buyZone:[4250,4480],take:5850,stop:4020,note:'AIデータセンター向け光配線が強い。一方で期待先行の過熱に注意。'},
 {code:'4082',name:'第一稀元素化学工業',price:1080,theme:['レアアース','自動車触媒'],fund:70,themeScore:90,valuation:84,technical:71,flow:68,catalyst:88,buy:82,upside:62,action:'押し目候補',buyZone:[1010,1060],take:1450,stop:940,note:'ジルコニウム化合物の世界級メーカー。資源安保と電池材料の展開を監視。'},
 {code:'4973',name:'日本高純度化学',price:3260,theme:['先端めっき','半導体'],fund:79,themeScore:83,valuation:75,technical:68,flow:62,catalyst:70,buy:73,upside:38,action:'監視',buyZone:[3050,3180],take:4100,stop:2880,note:'電子部品向け貴金属めっき薬品の高収益ニッチ。用途拡大が鍵。'},
 {code:'7717',name:'ブイ・テクノロジー',price:2910,theme:['半導体検査','ディスプレイ'],fund:67,themeScore:85,valuation:81,technical:65,flow:58,catalyst:76,buy:74,upside:51,action:'監視',buyZone:[2700,2850],take:3900,stop:2520,note:'検査・露光技術の半導体用途拡大と受注残の質を確認。'},
 {code:'6472',name:'NTN',price:342,theme:['ベアリング','EV'],fund:65,themeScore:66,valuation:91,technical:70,flow:69,catalyst:65,buy:77,upside:39,action:'押し目候補',buyZone:[325,338],take:430,stop:303,note:'低PBRの再評価候補。構造改革と利益率改善が株価材料。'},
 {code:'6323',name:'ローツェ',price:1985,theme:['半導体搬送','自動化'],fund:91,themeScore:91,valuation:57,technical:78,flow:75,catalyst:82,buy:74,upside:44,action:'押し目待ち',buyZone:[1800,1920],take:2520,stop:1680,note:'前工程搬送の成長性は高い。半導体設備投資循環と受注を監視。'}
];
const WEIGHTS={fund:.25,themeScore:.20,valuation:.15,technical:.20,flow:.10,catalyst:.10};
let stocks=STOCKS.map(s=>({...s,score:Math.round(Object.entries(WEIGHTS).reduce((n,[k,w])=>n+s[k]*w,0))}));
let selected=stocks[0];
let watch=new Set(JSON.parse(localStorage.getItem('tadyam-watch')||'[]'));
let holdings=JSON.parse(localStorage.getItem('tadyam-holdings')||'[{"code":"1969","shares":100,"cost":4220},{"code":"3436","shares":200,"cost":1650},{"code":"5803","shares":100,"cost":4650},{"code":"4082","shares":100,"cost":1080}]');
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n);
function sorted(list=stocks){const q=document.querySelector('#searchInput').value.toLowerCase();const key=document.querySelector('#sortSelect').value;return list.filter(s=>`${s.code}${s.name}${s.theme.join('')}`.toLowerCase().includes(q)).sort((a,b)=>b[key]-a[key]);}
function card(s,i){return `<article class="stock-card" data-code="${s.code}"><div class="rank ${i<3?'top':''}">${String(i+1).padStart(2,'0')}</div><div><span class="stock-code">${s.code}</span><div class="stock-name">${s.name}</div><div class="tags">${s.theme.map(t=>`<span class="tag">${t}</span>`).join('')} <span class="action ${s.action==='過熱注意'?'hot':''}">${s.action}</span></div></div><div class="score"><button class="watch ${watch.has(s.code)?'on':''}" data-watch="${s.code}" aria-label="監視リスト切替">★</button><strong>${s.score}</strong><small>/100</small><span class="upside">上値余地 +${s.upside}%</span></div></article>`}
function bindCards(){document.querySelectorAll('.stock-card').forEach(el=>el.onclick=e=>{if(e.target.dataset.watch){e.stopPropagation();toggleWatch(e.target.dataset.watch);return}selected=stocks.find(s=>s.code===el.dataset.code);showView('analysis');renderAnalysis()})}
function renderRanking(){const list=sorted().slice(0,10);document.querySelector('#rankingGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">該当する銘柄がありません</div>';const top=list[0];if(top){document.querySelector('#heroCode').textContent=top.code;document.querySelector('#heroName').textContent=top.name}bindCards()}
function renderAnalysis(){const s=selected;const labels=[['業績',s.fund],['テーマ',s.themeScore],['割安度',s.valuation],['チャート',s.technical],['需給',s.flow],['材料',s.catalyst]];document.querySelector('#analysisPanel').innerHTML=`<div class="analysis-top"><div><p class="eyebrow">STOCK ANALYSIS</p><span class="stock-code">${s.code}</span><h2>${s.name}</h2><div class="price">${yen(s.price)} <span class="action">${s.action}</span></div><div class="tags">${s.theme.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div class="big-score" style="--score:${s.score}"><strong>${s.score}</strong></div></div><div class="metrics">${labels.map(([l,v])=>`<div class="metric"><span>${l}</span><strong>${v}</strong></div>`).join('')}</div><div class="zones"><div class="zone"><span>買いゾーン</span><b>${yen(s.buyZone[0])}〜${yen(s.buyZone[1])}</b></div><div class="zone"><span>利確目安</span><b class="positive">${yen(s.take)}</b></div><div class="zone"><span>損切り目安</span><b class="negative">${yen(s.stop)}</b></div></div><div class="notes"><strong>分析メモ</strong><br>${s.note}</div>`}
function toggleWatch(code){watch.has(code)?watch.delete(code):watch.add(code);localStorage.setItem('tadyam-watch',JSON.stringify([...watch]));renderAll()}
function renderWatch(){const list=stocks.filter(s=>watch.has(s.code));document.querySelector('#watchCount').textContent=list.length;document.querySelector('#watchGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">星マークを押すと、ここに銘柄が並びます。</div>';bindCards()}
function renderPortfolio(){let value=0,cost=0;document.querySelector('#portfolioRows').innerHTML=holdings.map((h,i)=>{const s=stocks.find(x=>x.code===h.code);if(!s)return'';const pnl=(s.price-h.cost)*h.shares;value+=s.price*h.shares;cost+=h.cost*h.shares;return `<tr><td><strong>${s.code} ${s.name}</strong></td><td>${h.shares.toLocaleString()}株</td><td>${yen(h.cost)}</td><td>${yen(s.price)}</td><td class="${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}${yen(pnl)}</td><td><button class="remove" data-remove="${i}">削除</button></td></tr>`}).join('');const pnl=value-cost;document.querySelector('#portfolioSummary').innerHTML=`<div class="summary-card"><span>評価額</span><strong>${yen(value)}</strong></div><div class="summary-card"><span>評価損益</span><strong class="${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}${yen(pnl)}</strong></div>`;document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{holdings.splice(+b.dataset.remove,1);saveHoldings()})}
function saveHoldings(){localStorage.setItem('tadyam-holdings',JSON.stringify(holdings));renderPortfolio()}
function showView(id){document.querySelectorAll('.view,.tab').forEach(x=>x.classList.remove('active'));document.querySelector(`#${id}`).classList.add('active');document.querySelector(`[data-view="${id}"]`).classList.add('active')}
function renderAll(){renderRanking();renderWatch();renderPortfolio();renderAnalysis()}
function analyzeSearch(){const q=document.querySelector('#searchInput').value.trim().toLowerCase();const match=stocks.find(s=>s.code===q)||stocks.find(s=>s.name.toLowerCase().includes(q));if(match){selected=match;showView('analysis');renderAnalysis();return}if(/^\d{4}$/.test(q)){document.querySelector('#rankingGrid').innerHTML=`<div class="empty"><strong>${q}</strong> はまだ分析データに登録されていません。<br>対象銘柄を順次追加しています。</div>`;showView('ranking')}else{renderRanking()}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showView(b.dataset.view));const searchInput=document.querySelector('#searchInput');searchInput.oninput=renderRanking;searchInput.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();analyzeSearch()}};document.querySelector('#analyzeButton').onclick=analyzeSearch;document.querySelector('#sortSelect').onchange=renderRanking;
const dialog=document.querySelector('#holdingDialog');document.querySelector('#addHolding').onclick=()=>dialog.showModal();document.querySelector('#holdingStock').innerHTML=stocks.map(s=>`<option value="${s.code}">${s.code} ${s.name}</option>`).join('');document.querySelector('#holdingForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;holdings.push({code:document.querySelector('#holdingStock').value,shares:+document.querySelector('#holdingShares').value,cost:+document.querySelector('#holdingCost').value});saveHoldings()};
document.querySelector('#csvInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const lines=reader.result.trim().split(/\r?\n/);const head=lines.shift().split(',').map(x=>x.trim());for(const line of lines){const row=line.split(',');const o=Object.fromEntries(head.map((h,i)=>[h,row[i]?.trim()]));const s=stocks.find(x=>x.code===o.code);if(s&&o.price)s.price=+o.price}renderAll();alert('CSVから参考株価を更新しました')};reader.readAsText(file)};
document.querySelector('#dataDate').textContent='評価基準日 2026/09/10・サンプルデータ';renderAll();
