const STOCKS=[
 {code:'1969',name:'高砂熱学工業',price:4220,theme:['データセンター冷却','設備工事'],fund:88,themeScore:94,valuation:70,technical:76,flow:74,catalyst:86,buy:84,upside:42,action:'押し目候補',buyZone:[4050,4180],take:5400,stop:3820,note:'AIデータセンターの冷却・省エネ投資が追い風。受注と利益率を継続確認。'},
 {code:'4052',name:'フィーチャ',price:612,theme:['DMS','車載AI'],fund:62,themeScore:93,valuation:58,technical:66,flow:60,catalyst:88,buy:78,upside:85,action:'監視',buyZone:[560,600],take:980,stop:515,note:'累計ライセンス台数、ライセンス売上、量産案件数、大手OEM案件への移行が最重要。'},
 {code:'3687',name:'フィックスターズ',price:2115,theme:['AI高速化','量子'],fund:82,themeScore:92,valuation:52,technical:73,flow:72,catalyst:84,buy:76,upside:55,action:'押し目待ち',buyZone:[1900,2040],take:2850,stop:1780,note:'高速化ソフトの利益成長と量子・AI案件の実需化を確認。'},
 {code:'3436',name:'SUMCO',price:1650,theme:['半導体ウエハ'],fund:58,themeScore:78,valuation:82,technical:63,flow:61,catalyst:72,buy:75,upside:48,action:'押し目候補',buyZone:[1560,1640],take:2180,stop:1460,note:'シリコンウエハ市況の底打ちと稼働率回復が焦点。'},
 {code:'5803',name:'フジクラ',price:4650,theme:['光電融合','データセンター'],fund:95,themeScore:97,valuation:45,technical:84,flow:88,catalyst:90,buy:71,upside:36,action:'過熱注意',buyZone:[4250,4480],take:5850,stop:4020,note:'AIデータセンター向け光配線が強い。一方で期待先行の過熱に注意。'},
 {code:'4082',name:'第一稀元素化学工業',price:1080,theme:['レアアース','自動車触媒'],fund:70,themeScore:90,valuation:84,technical:71,flow:68,catalyst:88,buy:82,upside:62,action:'押し目候補',buyZone:[1010,1060],take:1450,stop:940,note:'ジルコニウム化合物の世界級メーカー。資源安保と電池材料の展開を監視。'},
 {code:'4973',name:'日本高純度化学',price:3260,theme:['先端めっき','半導体'],fund:79,themeScore:83,valuation:75,technical:68,flow:62,catalyst:70,buy:73,upside:38,action:'監視',buyZone:[3050,3180],take:4100,stop:2880,note:'電子部品向け貴金属めっき薬品の高収益ニッチ。用途拡大が鍵。'},
 {code:'7717',name:'ブイ・テクノロジー',price:2910,theme:['半導体検査','ディスプレイ'],fund:67,themeScore:85,valuation:81,technical:65,flow:58,catalyst:76,buy:74,upside:51,action:'監視',buyZone:[2700,2850],take:3900,stop:2520,note:'検査・露光技術の半導体用途拡大と受注残の質を確認。'},
 {code:'6472',name:'NTN',price:342,theme:['ベアリング','EV'],fund:65,themeScore:66,valuation:91,technical:70,flow:69,catalyst:65,buy:77,upside:39,action:'押し目候補',buyZone:[325,338],take:430,stop:303,note:'低PBRの再評価候補。構造改革と利益率改善が株価材料。'},
 {code:'6323',name:'ローツェ',price:1985,theme:['半導体搬送','自動化'],fund:91,themeScore:91,valuation:57,technical:78,flow:75,catalyst:82,buy:74,upside:44,action:'押し目待ち',buyZone:[1800,1920],take:2520,stop:1680,note:'前工程搬送の成長性は高い。半導体設備投資循環と受注を監視。'}
];
const HISTORY_STOCKS=[
 ['1414','ショーボンドホールディングス'],['1605','INPEX'],['1801','大成建設'],['1803','清水建設'],['1812','鹿島建設'],['1820','西松建設'],['1824','前田建設工業'],['1828','田辺工業'],['1844','大盛工業'],['1879','新日本建設'],['1885','東亜建設工業'],['1888','若築建設'],['1893','五洋建設'],['1926','ライト工業'],['1944','きんでん'],['1949','住友電設'],['1959','九電工'],['1961','三機工業'],['1963','日揮ホールディングス'],['1979','大氣社'],
 ['2138','クルーズ'],['2325','NJS'],['2329','東北新社'],['2638','グローバルX ロボティクス＆AI-日本株式 ETF'],['2760','東京エレクトロン デバイス'],['3036','アルコニックス'],['3110','日東紡績'],['3132','マクニカホールディングス'],['3156','レスター'],['3350','メタプラネット'],['3445','RS Technologies'],['3449','テクノフレックス'],['3454','ファーストブラザーズ'],['3652','ディジタルメディアプロフェッショナル'],['3719','AIストーム'],['3778','さくらインターネット'],['3825','リミックスポイント'],
 ['4023','クレハ'],['4062','イビデン'],['4063','信越化学工業'],['4186','東京応化工業'],['4642','オリジナル設計'],['4813','ACCESS'],['4970','東洋合成工業'],['4971','メック'],['5016','JX金属'],['5020','ENEOSホールディングス'],['5217','テクノクオーツ'],['5259','BBDイニシアティブ'],['5268','旭コンクリート工業'],['5287','イトーヨーギョー'],['5401','日本製鉄'],['5411','JFEホールディングス'],['5631','日本製鋼所'],['5706','三井金属鉱業'],['5711','三菱マテリアル'],['5713','住友金属鉱山'],['5714','DOWAホールディングス'],['5715','古河機械金属'],['5721','エス・サイエンス'],
 ['5801','古河電気工業'],['5802','住友電気工業'],['5821','平河ヒューテック'],['5984','兼房'],['5986','モリテック スチール'],['6055','ジャパンマテリアル'],['6137','小池酸素工業'],['6146','ディスコ'],['6151','日東工器'],['6157','日進工具'],['6210','TOYOイノベックス'],['6227','AIメカテック'],['6235','オプトラン'],['6254','野村マイクロ・サイエンス'],['6266','タツモ'],['6268','ナブテスコ'],['6269','三井海洋開発'],['6291','日本エアーテック'],['6293','日精樹脂工業'],['6298','ワイエイシイホールディングス'],['6305','日立建機'],['6315','TOWA'],['6324','ハーモニック・ドライブ・システムズ'],['6361','荏原製作所'],['6363','酉島製作所'],['6367','ダイキン工業'],['6378','木村化工機'],['6390','加藤製作所'],['6471','日本精工'],['6472','NTN'],['6492','岡野バルブ製造'],
 ['6501','日立製作所'],['6503','三菱電機'],['6504','富士電機'],['6506','安川電機'],['6508','明電舎'],['6521','オキサイド'],['6525','KOKUSAI ELECTRIC'],['6526','ソシオネクスト'],['6544','ジャパンエレベーターサービスホールディングス'],['6574','コンヴァノ'],['6590','芝浦メカトロニクス'],['6592','マブチモーター'],['6594','ニデック'],['6613','QDレーザ'],['6637','寺崎電気産業'],['6701','NEC'],['6752','パナソニック ホールディングス'],['6754','アンリツ'],['6762','TDK'],['6769','ザインエレクトロニクス'],['6814','古野電気'],['6855','日本電子材料'],['6856','堀場製作所'],['6857','アドバンテスト'],['6918','アバールデータ'],['6920','レーザーテック'],['6946','日本アビオニクス'],['6951','日本電子'],['6954','ファナック'],['6958','日本CMK'],['6960','フクダ電子'],['6961','エンプラス'],['6963','ローム'],['6965','浜松ホトニクス'],['6988','日東電工'],['6994','指月電機製作所'],['6996','ニチコン'],
 ['7003','三井E&S'],['7011','三菱重工業'],['7012','川崎重工業'],['7013','IHI'],['7279','ハイレックスコーポレーション'],['7460','ヤギ'],['7467','萩原電気ホールディングス'],['7539','アイナボホールディングス'],['7701','島津製作所'],['7721','東京計器'],['7729','東京精密'],['7735','SCREENホールディングス'],['7745','A&Dホロンホールディングス'],['7769','リズム'],['7794','イーディーピー'],['7841','遠藤製作所'],['8031','三井物産'],['8035','東京エレクトロン'],['8058','三菱商事'],['8105','堀田丸正'],['8154','加賀電子'],['8159','立花エレテック'],['8630','SOMPOホールディングス'],['8801','三井不動産'],['8802','三菱地所'],['8881','日神グループホールディングス'],['8951','日本ビルファンド投資法人'],['8952','ジャパンリアルエステイト投資法人'],['8976','大和証券オフィス投資法人'],['8999','グランディハウス'],
 ['9101','日本郵船'],['9348','ispace'],['9412','スカパーJSATホールディングス'],['9432','NTT'],['9503','関西電力'],['9513','J-POWER'],['9551','メタウォーター'],['9613','NTTデータグループ'],['9616','共立メンテナンス'],['9678','カナモト'],['9755','応用地質'],['9983','ファーストリテイリング'],['9984','ソフトバンクグループ']
];
const WEIGHTS={fund:.25,themeScore:.20,valuation:.15,technical:.20,flow:.10,catalyst:.10};
const pendingStock=([code,name])=>({code,name,price:0,theme:['過去会話銘柄','自動分析中'],fund:null,themeScore:null,valuation:null,technical:null,flow:null,catalyst:null,buy:0,upside:0,action:'データ取得中',buyZone:[0,0],take:0,stop:0,note:'無料市場データを使った自動分析を準備しています。',pending:true});
let stocks=[...STOCKS,...HISTORY_STOCKS.filter(([code])=>!STOCKS.some(s=>s.code===code)).map(pendingStock)].map(s=>({...s,score:s.pending?0:Math.round(Object.entries(WEIGHTS).reduce((n,[k,w])=>n+s[k]*w,0))}));
let selected=stocks[0];
let watch=new Set(JSON.parse(localStorage.getItem('tadyam-watch')||'[]'));
let holdings=JSON.parse(localStorage.getItem('tadyam-holdings')||'[]');
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n);
function sorted(list=stocks){const q=document.querySelector('#searchInput').value.toLowerCase();const key=document.querySelector('#sortSelect').value;return list.filter(s=>`${s.code}${s.name}${s.theme.join('')}`.toLowerCase().includes(q)).sort((a,b)=>b[key]-a[key]);}
function card(s,i){return `<article class="stock-card" data-code="${s.code}"><div class="rank ${i<3?'top':''}">${String(i+1).padStart(2,'0')}</div><div><span class="stock-code">${s.code}</span><div class="stock-name">${s.name}<span class="stock-price ${s.price?'':'loading'}">${s.price?yen(s.price):'株価取得中'}</span></div><div class="tags">${s.theme.map(t=>`<span class="tag">${t}</span>`).join('')} <span class="action ${s.action==='過熱注意'?'hot':''}">${s.action}</span></div></div><div class="score"><button class="watch ${watch.has(s.code)?'on':''}" data-watch="${s.code}" aria-label="監視リスト切替">★</button><strong>${s.score||'—'}</strong><small>${s.score?'/100':''}</small>${s.upside? `<span class="upside">上値余地 +${s.upside}%</span>`:''}</div></article>`}
function bindCards(){document.querySelectorAll('.stock-card').forEach(el=>el.onclick=e=>{if(e.target.dataset.watch){e.stopPropagation();toggleWatch(e.target.dataset.watch);return}selected=stocks.find(s=>s.code===el.dataset.code);showView('analysis');renderAnalysis()})}
function renderRanking(){const list=sorted().slice(0,10);document.querySelector('#rankingGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">該当する銘柄がありません</div>';const top=list[0];if(top){document.querySelector('#heroCode').textContent=top.code;document.querySelector('#heroName').textContent=top.name}bindCards()}
function renderAnalysis(){const s=selected;const labels=[['業績',s.fund],['テーマ',s.themeScore],['割安度',s.valuation],['チャート',s.technical],['需給',s.flow],['材料',s.catalyst]];const hasData=s.price>0;document.querySelector('#analysisPanel').innerHTML=`<div class="analysis-top"><div><p class="eyebrow">STOCK ANALYSIS</p><span class="stock-code">${s.code}</span><h2>${s.name}<span class="stock-price ${hasData?'':'loading'}">${hasData?yen(s.price):'株価取得中'}</span></h2><div class="price"><span class="action">${s.action}</span></div><div class="tags">${s.theme.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div class="big-score" style="--score:${s.score}"><strong>${s.score||'—'}</strong></div></div><div class="metrics">${labels.map(([l,v])=>`<div class="metric"><span>${l}</span><strong>${v??'—'}</strong></div>`).join('')}</div><div class="zones"><div class="zone"><span>買いゾーン</span><b>${hasData?`${yen(s.buyZone[0])}〜${yen(s.buyZone[1])}`:'データ取得中'}</b></div><div class="zone"><span>利確目安</span><b class="positive">${hasData?yen(s.take):'データ取得中'}</b></div><div class="zone"><span>損切り目安</span><b class="negative">${hasData?yen(s.stop):'データ取得中'}</b></div></div><div class="notes"><strong>分析メモ</strong><br>${s.note}</div>`}
function toggleWatch(code){watch.has(code)?watch.delete(code):watch.add(code);localStorage.setItem('tadyam-watch',JSON.stringify([...watch]));renderAll()}
function renderWatch(){const list=stocks.filter(s=>watch.has(s.code));document.querySelector('#watchCount').textContent=list.length;document.querySelector('#watchGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">星マークを押すと、ここに銘柄が並びます。</div>';bindCards()}
function renderPortfolio(){let value=0,cost=0;document.querySelector('#portfolioRows').innerHTML=holdings.map((h,i)=>{const s=stocks.find(x=>x.code===h.code);if(!s)return'';const pnl=(s.price-h.cost)*h.shares;value+=s.price*h.shares;cost+=h.cost*h.shares;return `<tr><td><strong>${s.code} ${s.name}</strong></td><td>${h.shares.toLocaleString()}株</td><td>${yen(h.cost)}</td><td>${yen(s.price)}</td><td class="${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}${yen(pnl)}</td><td><button class="remove" data-remove="${i}">削除</button></td></tr>`}).join('');const pnl=value-cost;document.querySelector('#portfolioSummary').innerHTML=`<div class="summary-card"><span>評価額</span><strong>${yen(value)}</strong></div><div class="summary-card"><span>評価損益</span><strong class="${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}${yen(pnl)}</strong></div>`;document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{holdings.splice(+b.dataset.remove,1);saveHoldings()})}
function saveHoldings(){localStorage.setItem('tadyam-holdings',JSON.stringify(holdings));renderPortfolio()}
function showView(id){document.querySelectorAll('.view,.tab').forEach(x=>x.classList.remove('active'));document.querySelector(`#${id}`).classList.add('active');document.querySelector(`[data-view="${id}"]`).classList.add('active')}
function renderAll(){renderRanking();renderWatch();renderPortfolio();renderAnalysis()}
function analyzeSearch(){const q=document.querySelector('#searchInput').value.trim().toLowerCase();const match=stocks.find(s=>s.code===q)||stocks.find(s=>s.name.toLowerCase().includes(q));if(match){selected=match;showView('analysis');renderAnalysis();return}if(/^\d{4}$/.test(q)){document.querySelector('#rankingGrid').innerHTML=`<div class="empty"><strong>${q}</strong> はまだ分析データに登録されていません。<br>対象銘柄を順次追加しています。</div>`;showView('ranking')}else{renderRanking()}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showView(b.dataset.view));const searchInput=document.querySelector('#searchInput');searchInput.oninput=renderRanking;searchInput.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();analyzeSearch()}};document.querySelector('#analyzeButton').onclick=analyzeSearch;document.querySelector('#sortSelect').onchange=renderRanking;
const dialog=document.querySelector('#holdingDialog');document.querySelector('#addHolding').onclick=()=>dialog.showModal();document.querySelector('#holdingStock').innerHTML=stocks.map(s=>`<option value="${s.code}">${s.code} ${s.name}</option>`).join('');document.querySelector('#holdingForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;holdings.push({code:document.querySelector('#holdingStock').value,shares:+document.querySelector('#holdingShares').value,cost:+document.querySelector('#holdingCost').value});saveHoldings()};
document.querySelector('#csvInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const lines=reader.result.trim().split(/\r?\n/);const head=lines.shift().split(',').map(x=>x.trim());for(const line of lines){const row=line.split(',');const o=Object.fromEntries(head.map((h,i)=>[h,row[i]?.trim()]));const s=stocks.find(x=>x.code===o.code);if(s&&o.price)s.price=+o.price}renderAll();alert('CSVから参考株価を更新しました')};reader.readAsText(file)};
async function loadMarketData(){try{const response=await fetch('data/market.json',{cache:'no-store'});if(!response.ok)throw new Error('market data unavailable');const payload=await response.json();for(const row of payload.stocks||[]){const s=stocks.find(x=>x.code===row.code);if(!s)continue;Object.assign(s,{price:row.price,technical:row.technical,flow:row.flow,score:row.score,buy:row.score,action:row.action,buyZone:row.buy_zone,take:row.take,stop:row.stop,upside:row.upside,theme:s.pending?['過去会話銘柄','テクニカル分析']:s.theme,note:`無料市場データによる自動分析。25日線 ${yen(row.sma25)}、75日線 ${yen(row.sma75)}、RSI14 ${row.rsi14}、出来高比 ${row.volume_ratio}倍。業績・テーマ・割安度・材料は未採点です。`,pending:false})}document.querySelector('#dataDate').textContent=`市場データ更新 ${payload.updated_at||'—'}`;renderAll()}catch(e){document.querySelector('#dataDate').textContent='市場データを準備中';renderAll()}}
document.querySelector('#dataDate').textContent='市場データを準備中';renderAll();loadMarketData();
